Fix theme selectior css
camptocamp/ngeo pull request #6438
Opened 2020-11-10 16:15 UTC by arnaud-morvan

May be a good practice to always put the sass variable as default value in var() instead of duplicting the rule.
Seems that var parameter declaration-value is there exactly for that.

2020-11-11 07:04 UTC, ger-benjamin approved these changes
+1, there is a lot occurrence (probably harmless) of these "double-definition" that we should replace with this use of the var.

2020-11-11 10:40 UTC, sbrunner commented
The first line is for IE then it shouldn't be removed...

2020-11-11 10:41 UTC, sbrunner requested changes
There is an issue that --theme-selector-columns is not always defined?

2020-11-12 08:49 UTC, arnaud-morvan commented
@sbrunner:
Yes theme selector is broken on GMF 2.6 desktop app.
Seems that calc, with calls to `var()`, with not existing properties, does not return an empty value but a wrong value.
By adding `declaration-value` (default) parameterto var calls, it return the good value.

You're right, this PR breaks theme selector layout on IE.
I've restored the lines without call to var for IE.

2020-11-12 17:41 UTC, closed without merging